parameters:
    fox.elasticsearch_service.factory.class: Fox\ElasticsearchBundle\Factory\ElasticsearchServiceFactory

services:
    fox.elasticsearch_service.factory:
        class: %fox.elasticsearch_service.factory.class%
