parameters:
    es.factory.class: Fox\ElasticsearchBundle\Factory\ElasticsearchConnectionFactory
    es.factory.params:
        logPath: %kernel.logs_dir%/elasticsearch_%kernel.environment%.log
        tracePath: %kernel.logs_dir%/elasticsearch_trace_%kernel.environment%.log

services:
    es.factory:
        class: %es.factory.class%
        calls:
            - [addParams, [%es.factory.params%]]
