language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - elasticsearch
install:
  - "echo 'script.disable_dynamic: false' | sudo tee -a /etc/elasticsearch/elasticsearch.yml"
  - sudo service elasticsearch restart
before_script:
  - composer install
script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
